name: Rust

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - "main"
      - "dev"

env:
  CARGO_TERM_COLOR: always

jobs:
  test-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup update nightly && rustup default nightly && rustup component add rustfmt
    - name: Cargo fmt
      run: cargo +nightly fmt --all --check
      

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - 1.82
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v4
    - name: Install babeltrace2
      run: sudo apt-get install -y libbabeltrace2-dev
    - name: Set up toolchain
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - 1.82
          - stable
          - beta
          - nightly
        isDev:
          - ${{ github.ref == 'refs/heads/dev' }}
        exclude:
          # skip all toolchains except stable if dev branch
          - toolchain: 1.82
            isDev: true
          - toolchain: beta
            isDev: true
          - toolchain: nightly
            isDev: true
    steps:
    - uses: actions/checkout@v4
    - name: Install babeltrace2
      run: sudo apt-get install -y libbabeltrace2-dev
    - name: Set up toolchain
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Run tests
      run: cargo test --verbose